// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTWGzx0L9q0DqFKEWiTi_dMGXR4tyyfXs',
    appId: '1:1006781666360:android:77728bd9bdcae0cfc502cd',
    messagingSenderId: '1006781666360',
    projectId: 'flutter-login-app-b0e4e',
    storageBucket: 'flutter-login-app-b0e4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRG_Tse_k4tkBn0k-_3e_VsZJd8fXqSHE',
    appId: '1:1006781666360:ios:122796dc82147d20c502cd',
    messagingSenderId: '1006781666360',
    projectId: 'flutter-login-app-b0e4e',
    storageBucket: 'flutter-login-app-b0e4e.appspot.com',
    androidClientId: '1006781666360-tt0q48ntnjoualjtfhog5rek6a51d2km.apps.googleusercontent.com',
    iosClientId: '1006781666360-bq9p0qmukpbgkv3n1ijjnhqf23k356ck.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFlutterApp',
  );
}
